### ISSUE TITLE
Numeric usernames cause "Invalid Key" error

### ISSUE THREAD

**Issue by carlobolla** [MBmasher/osu-calc-length-bonus#2]
Using the profile-calc.exe and inputting an username containing numbers such as "Massimo99" or "carlo99bolla" (last one non existant) the program wil return the "Invalid API key" error.
![Screenshot](https://user-images.githubusercontent.com/14152206/47323846-cb8b3280-d65d-11e8-9e5d-cb14785a5642.png)

**Comment by carlobolla** [comment]
Update 1: Turns out that the first user is restricted, and the second user in non existant so it's correct for the JSONs to not return anything. Nonetheless i think the error text should be more explicative.
![Screenshot](https://user-images.githubusercontent.com/14152206/47410978-b39fd580-d767-11e8-8a16-7f60ee2d5af8.png)

**Comment by MBmasher** [comment]
Fixed in latest commit.
