### ISSUE TITLE
Invalid virus detections?

### ISSUE THREAD

**Issue by masamesa** [MBmasher/osu-calc-length-bonus#3]
Hi, I wanted to give you a heads up that there's a few invalid virus detections, unsure if you can get them resolved since it makes the file look sketch. https://www.virustotal.com/#/file/a76f928f42d6dd017cb47fdff3cd90dc41cefc23e40805cce3a361cbb860c6ab/detection

**Comment by MBmasher** [comment]
Apparently what I've done is also being done in malware files (which is compiling Python into an exe file), so you'll just have to trust that the exe files that I've provided are safe.

**Comment by MBmasher** [comment]
close
