### ISSUE TITLE
stop

### ISSUE THREAD

**Issue by hazel0177** [MBmasher/osu-calc-length-bonus#4]
this is bad

**Comment by cmyui** [comment]
> this is bad

destruction 100

**Comment by jacksonisiah** [comment]
> >    this is bad

> destruction 100

+1

**Comment by hazel0177** [comment]
i apologise for this rude and insensitive issue

**Comment by insomnyawolf** [comment]
it is actually horrible

**Comment by hazel0177** [comment]
good to know we're all in agreeement

**Comment by MBmasher** [comment]
what

**Comment by hazel0177** [comment]
this is literally the worst pp change i've ever seen please do not persue this

thank you
