### ISSUE TITLE
Float division by zero on some scores in profile-calc v3.1

### ISSUE THREAD

**Issue by vietnam13231** [MBmasher/osu-calc-length-bonus#5]
Some scores gets this error in console:
('Error processing this beatmap. Exception: division by zero'. 0, 0),
with basically the same error in calc ui. Example: 65th score in WubWoofWolf profile (Bloodhound Gang - Mope (Insane) by Hitoshirenu Shourai).

Edit:Forgot to add. When clicking "Sort by Percent Change" there is some new things jumping out:
Exception in Tkinter callback
Traceback (most recent call last):
      File "tkinter\_init_.pp", line 1702, in _call_
      File "profile_gui.py", line 126, in <lambda>
      File "profile_gui.py", line 29, in sort_values
      File "profile_gui.py", line 29, in <lambda>
ZeroDivisionError: float division by zero

Program doesn't crash, just ignores that button.

**Comment by MBmasher** [comment]
It was a problem with old osu file formats, fixed.
